#+title: 66% of Nixpkgs are up-to-date
#+author: Matthew Bauer
#+date: <2018-03-29 Thu>

Just wanted to congratulate everyone for all of the work in keeping
Nixpkgs up-to-date!

Repology has just updated our stats and we have shown significant
improvement. 66% of nixpkgs-unstable packages are up-to-date, with a
total of 6112 up-to-date packages[fn:1]. Nixpkgs is slowly growing to
match package sets that come in many of the big Linux distros. We now
have more up-to-date packages than rolling release distros Arch (5924)
and Manjaro (5708)! We certainly have a ways to go to compete with
heavyweights like FreeBSD Ports (15410), DragonFly BSD Ports (14268),
and Debian (14915) but these are ancient projects that have had a huge
headstart. We are definitely making progress and it’s visible in the
Repology graphs[fn:2].

For comparison, in February, nixpkgs-unstable had 60% of packages
up-to-date, with a total of 5439 up-to-date packages[fn:3]. This kind
of progress over 1 month is tremendously helpful. Remember that most
of these updates will be included in 18.09, not the soon to be release
18.03. This protects users from potentially breaking changes as well
as giving maintainers plenty of time to verify that the updates have
not had any negative effects.

Ryan Mulligan’s [[https://github.com/ryantm/nix-update][nix-update]] has made updating packages much easier and
I think it will be a game changer for Nixpkgs in the long run. There
are still some kinks in it but I think it is slowly getting better. It
has certainly been a headache to handle the huge increase in pull
requests, but we are slowly clearing through that glut of outdated
software. If an update to nixpkgs-unstable breaks something for you,
please be sure to open an issue.

[fn:1] https://repology.org/statistics/newest
[fn:2] https://repology.org/repository/nix_unstable
[fn:3] https://web.archive.org/web/20180216091523/https://repology.org/statistics/newest
